// coffeed-client/src/layout/header/Header.tsx
import classes from "./Header.module.scss"
import logo from "../../assets/logov3.svg"

const Header = () => (
  <header className={classes.header}>
    <img className={classes.logo} src={logo} alt="Coffeed logo" />
    <nav className={classes.navbar}>
      <ul className={classes.menu}>
        <li className={classes.item}>
          <a>Homepage</a>
        </li>
        <li className={classes.item}>
          <a>About</a>
        </li>
        <li className={classes.item}>
          <a>Shop</a>
        </li>
        <li className={classes.item}>
          <a>Blog</a>
        </li>
        <li className={classes.item}>
          <a>Contact us</a>
        </li>
      </ul>
    </nav>
  </header>
)

export default Header

// coffeed-client/src/layout/Header/Header.vue
<template>
    <header>
        <img src="../../assets/logo/logov3.svg" alt="Coffeed logo">
            <nav>
      <ul>
        <li><router-link to="/">Homepage</router-link></li>
        <li><router-link to="/about">About</router-link></li>
        <li><router-link to="/shop">Shop</router-link></li>
        <li><router-link to="/blog">Blog</router-link></li>
        <li><router-link to="#">Contact us</router-link></li>
      </ul>
    </nav>

    </header>
</template>

<style lang="scss" scoped>
@import "../../style/variables.scss";

header {
  background-color: $black;
  display: flex;
  flex-flow: column;
  width: 100%;
  height: 100%;
  padding-top: 1rem;

  img {
    height: 10rem;
    width: auto;
  }

  nav {
    display: flex;
    justify-content: center;
    margin-top: 0.25rem;
    margin-bottom: 1rem;

    ul {
      list-style-type: none;
      margin: 0;
      padding: 0;
      overflow: hidden;

      li {
        float: left;

        a {
          transition: all 0.5s;
          display: block;
          color: $white;
          text-align: center;
          padding: 14px 16px;
          text-decoration: none;
          border-bottom: 2px double $white;

          &:hover {
            background-color: $primary;
            border-bottom: 2px double $tertiary;
          }
        }
      }
    }
  }
}
</style>

<script lang="ts">
import { Component, Prop, Vue } from "vue-property-decorator"

@Component
export default class Header extends Vue {}
</script>
